In [3]:
import exifread
from PIL import Image

path = "/Users/anubhav/Downloads/Virat-Kohli-India-celebrates-50th-century-Cricket-November-15-2023.jpg.webp"

with open(path, 'rb') as f:
    tags = exifread.process_file(f)
for tag in tags.keys():
    print(f"{tag}: {tags[tag]}")
with Image.open(path) as img:
    print(f"Format: {img.format}")
    print(f"Size: {img.size}")
    print(f"Mode: {img.mode}")

import numpy as np

with Image.open(path) as img:
    # Convert image to NumPy array
    img_array = np.array(img)
    print(img_array.shape)  # Print the shape of the array
    print(img_array)  # Print the pixel data

Webp file does not have exif data.


Format: WEBP
Size: (1600, 1055)
Mode: RGB
(1055, 1600, 3)
[[[126 127 163]
  [126 127 163]
  [127 128 164]
  ...
  [ 38  76 154]
  [ 38  78 155]
  [ 36  78 155]]

 [[126 127 163]
  [126 127 163]
  [127 128 164]
  ...
  [ 38  76 154]
  [ 38  78 155]
  [ 36  78 155]]

 [[126 127 163]
  [126 127 163]
  [127 128 164]
  ...
  [ 39  77 155]
  [ 39  79 156]
  [ 37  80 156]]

 ...

 [[ 63  77 102]
  [ 63  77 102]
  [ 63  77 102]
  ...
  [ 71  66  84]
  [ 71  66  84]
  [ 71  66  84]]

 [[ 63  77 102]
  [ 63  77 102]
  [ 63  77 102]
  ...
  [ 71  66  84]
  [ 71  66  84]
  [ 71  66  84]]

 [[ 63  77 102]
  [ 63  77 102]
  [ 63  77 102]
  ...
  [ 71  66  84]
  [ 71  66  84]
  [ 71  66  84]]]
