In [2]:
import numpy as np

# Question 3: SVD Analysis - Direct answers only
A = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9],
    [1, 1, 1]
])

print("Matrix A:")
print(A)

# 1. Compute thin SVD
U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("\n1. Thin Singular Value Decomposition:")
print("A = UΣV^T where:")
print("\nU =")
np.set_printoptions(precision=6, suppress=True)
print(U)

print("\nΣ =")
Sigma = np.diag(s)
print(Sigma)

print("\nV =")
print(Vt.T)  # Transpose to get V from V^T

# 2. Rank
tolerance = 1e-10
rank = np.sum(s > tolerance)
print(f"\n2. Rank of A: {rank}")

# 3. Best rank-1 approximation SVD
sigma1 = s[0]
u1 = U[:, 0]
v1 = Vt[0, :]

print("\n3. Thin SVD of best rank-1 approximation:")
print(f"U₁ = {u1}")
print(f"Σ₁ = [{sigma1:.6f}]")
print(f"V₁ = {v1}")

# 4. Best rank-1 approximation matrix
A1 = sigma1 * np.outer(u1, v1)
print(f"\n4. Best rank-1 approximation A₁:")
print(A1)

# Verification
print(f"\nVerification - Reconstruction error: {np.linalg.norm(A - U @ Sigma @ Vt):.2e}")
print(f"Approximation error: {np.linalg.norm(A - A1):.6f}")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]]

1. Thin Singular Value Decomposition:
A = UΣV^T where:

U =
[[-0.213653  0.872565 -0.368568]
 [-0.517882  0.255209  0.472552]
 [-0.822111 -0.362148 -0.103984]
 [-0.10141  -0.205785 -0.793751]]

Σ =
[[16.935394  0.        0.      ]
 [ 0.        1.091988  0.      ]
 [ 0.        0.        0.      ]]

V =
[[-0.480731 -0.776035  0.408248]
 [-0.572471 -0.074905 -0.816497]
 [-0.66421   0.626225  0.408248]]

2. Rank of A: 2

3. Thin SVD of best rank-1 approximation:
U₁ = [-0.213653 -0.517882 -0.822111 -0.10141 ]
Σ₁ = [16.935394]
V₁ = [-0.480731 -0.572471 -0.66421 ]

4. Best rank-1 approximation A₁:
[[1.73943  2.071372 2.403314]
 [4.216269 5.020875 5.825481]
 [6.693108 7.970378 9.247648]
 [0.825613 0.983168 1.140722]]

Verification - Reconstruction error: 8.31e-16
Approximation error: 1.091988
